name: starter
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^2.0.7
  auto_route: ^7.8.0
  dio: ^5.3.2

  # ui
  animated_size_and_fade: ^3.0.1
  capped_progress_indicator: ^0.0.2
  animations: ^2.0.11
  gap:

  # storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # data
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # state
  riverpod: ^2.3.7
  flutter_riverpod: ^2.3.7
  hooks_riverpod: ^2.3.8
  flutter_hooks: ^0.20.0

  # logging
  talker_riverpod_logger: ^1.0.0
  talker_dio_logger: ^4.3.5
  talker_flutter: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  custom_lint: ^0.5.2
  riverpod_lint: ^2.2.0
  auto_route_generator: ^7.3.1
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/png/
    - assets/images/svg/

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    lottie: true
