name: app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  assets:
    path: ../packages/assets

  flutter_svg: ^2.0.16

  auto_route: ^10.1.0+1
  dio: ^5.7.0


  design:
    path: ../packages/design

  # storage
  flutter_secure_storage: ^9.2.3
  shared_preferences: ^2.3.5

  # data
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # state
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

  # logging
  talker_riverpod_logger: ^4.6.0
  talker_dio_logger: ^4.6.0
  talker_flutter: ^4.6.0

  # localization
  slang: ^4.4.1
  slang_flutter: ^4.4.0
  intl: 

  # utils
  jwt_decoder: ^2.0.1
  collection: ^1.19.0
  infinite_scroll_pagination: ^5.1.0
  quiver: ^3.2.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  freezed: ^3.0.6
  auto_route_generator: ^10.2.3
  slang_build_runner: ^4.4.0
  json_serializable: ^6.9.0
  index_generator: ^4.0.1

flutter:
  uses-material-design: true
