name: assets
description: >
  Holds the assets for the app. The assets are included in a
  separate package, to be able to share it with Widgetbook app.

version: 0.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
resolution: workspace
dependencies:
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.14

flutter:
  assets:
    - image/
    - svg/

flutter_gen:
  integrations:
    flutter_svg: true
  assets:
    outputs:
      package_parameter_enabled: true
