name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  app:
    path: ../../app
  widgetbook_annotation: ^3.2.0
  widgetbook: ^3.10.1
  design:
    path: ../design
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  widgetbook_generator: ^3.9.1

flutter:
  uses-material-design: true
